In [1]:
pip install numpy
np.set_printoptions(suppress=True, formatter={'float_kind': '{:0.1f}'.format})


Note: you may need to restart the kernel to use updated packages.


In [64]:
import numpy as np
num_arange1=np.arange(11)
num_arange2=np.arange(0.5,5,0.25)
print(num_arange1)
print(num_arange2)



[ 0  1  2  3  4  5  6  7  8  9 10]
[0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75
 4.   4.25 4.5  4.75]


In [68]:
zeros1=np.zeros(10, dtype=int)
zeros2=np.zeros((4,3), dtype=int)
print(zeros1)
print(zeros2)

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [70]:
linspace1=np.linspace(2,12,5, dtype=int)
linspace2=np.linspace(3,9,4, dtype=int)
print(linspace1)
print(linspace2)

[ 2  4  7  9 12]
[3 5 7 9]


In [80]:
random1=np.random.rand(4, 2)*0.999
random2=np.random.randint(10, 20, (3, 3))
random1_reshape=np.reshape(random1, (1,8))
# While using reshape you cannot use different amount of elements like here if you have a total of 8 numbers you can reshape it as you seem fit as long as it stays within those 8 numbers.
print(random1)
print(random2)
print(random1_reshape)

[[0.04225592 0.93687931]
 [0.99018231 0.28064097]
 [0.84329266 0.66796046]
 [0.93658251 0.40313687]]
[[19 18 11]
 [11 12 12]
 [15 13 14]]
[[0.04225592 0.93687931 0.99018231 0.28064097 0.84329266 0.66796046
  0.93658251 0.40313687]]


In [101]:
np.random.seed(42)
random_seed=np.random.rand(2,2)
print(random_seed)
print(random_seed)

# From what I can see if we use seed then no matter how many times we use print random we will get fixed numbers.
# The pros of using seed  is that you can test the same sequence over and over and you can keep that number sequence for later use. 

[[0.04872488 0.28910966]
 [0.72096635 0.02161625]]
[[0.04872488 0.28910966]
 [0.72096635 0.02161625]]
